version: '2'

services:
  redis:
    restart: always
    image: redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/sentry/redis:/data:Z

  postgresql:
    restart: always
    image: postgres:9.5
    volumes:
    - /srv/docker/sentry/postgresql:/var/run/postgresql:Z
    environment:
    - POSTGRES_USER=sentry
    - POSTGRES_PASSWORD=secret

  sentry:
    restart: always
    image: sentry:8.9-onbuild
    links:
    - redis
    - postgresql
    ports:
    - "8080:9000"
    volumes:
    - /srv/docker/sentry/sentry:/usr/src/sentry:Z
    command:
    - upgrade
    - run cron
    - run worker
    environment:
    - SENTRY_SECRET_KEY=$v2cy)eku@sjjv0uhd9c%6dlx3wn8)09(up7&gub*1u12am^_0
    # - SENTRY_POSTGRES_HOST
    # - SENTRY_POSTGRES_PORT
    # - SENTRY_DB_NAME
    # - SENTRY_DB_USER
    # - SENTRY_DB_PASSWORD

    # - SENTRY_REDIS_HOST
    # - SENTRY_REDIS_PORT
    # - SENTRY_REDIS_DB

    # - SENTRY_MEMCACHED_HOST
    # - SENTRY_MEMCACHED_PORT
    # - SENTRY_FILESTORE_DIR

    # - SENTRY_SERVER_EMAIL
    # - SENTRY_EMAIL_HOST
    # - SENTRY_EMAIL_PORT
    # - SENTRY_EMAIL_USER
    # - SENTRY_EMAIL_PASSWORD
    # - SENTRY_EMAIL_USE_TLS

  # sentry-cron:
  #   restart: always
  #   image: sentry:8.9-onbuild
  #   links:
  #   - redis
  #   - postgresql
  #   command:
  #   - run cron
  #   volumes:
  #   - /srv/docker/sentry/cron:/home/git/data:Z
  #   environment:
  #   - SENTRY_SECRET_KEY=$v2cy)eku@sjjv0uhd9c%6dlx3wn8)09(up7&gub*1u12am^_0    

  # sentry-worker:
  #   restart: always
  #   image: sentry:8.9-onbuild
  #   links:
  #   - redis
  #   - postgresql
  #   command:
  #   - run worker
  #   volumes:
  #   - /srv/docker/sentry/worker:/home/git/data:Z
  #   environment:
  #   - SENTRY_SECRET_KEY=$v2cy)eku@sjjv0uhd9c%6dlx3wn8)09(up7&gub*1u12am^_0  